name: "Continuous Integration"

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    name: "Test"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
        dependencies:
          - "lowest"
          - "highest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "xdebug"
          php-version: "${{ matrix.php-version }}"
          ini-values: "zend.assertions=1"

      - uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: "${{ matrix.dependencies }}"
      
      # dbal-fluid-schema-builder doesn't support v1.0 only v1.4
      - name: Update doctrine/inflector to v1.4 from v1.0
        if: "${{ 'lowest' == matrix.dependencies }}"
        run: |
          composer update doctrine/inflector:1.4 --ignore-platform-reqs

      - name: "Run PHPUnit"
        run: "vendor/bin/phpunit -c phpunit.xml.dist"

      - name: Upload coverage results to Coveralls
        # skip php-coversalls for lowest deps
        # it fails on lowest depedencies because old versions of guzzle doesn't work well with newer php versions
        if: "${{ 'highest' == matrix.dependencies }}"
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          vendor/bin/php-coveralls --coverage_clover=build/logs/clover.xml -v
